package com.saas.notification.controller;

import com.saas.notification.entity.Notification;
import com.saas.notification.repository.NotificationRepository;
import com.saas.notification.security.JwtSupport;
import com.saas.notification.service.NotificationService;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Read-side REST API for notifications, so a frontend can poll for real
 * notifications generated by the Kafka-driven event pipeline instead of
 * relying only on the STOMP/WebSocket push channel.
 */
@RestController
@RequestMapping("/api/notifications")
@CrossOrigin(origins = "*", maxAge = 3600)
public class NotificationController {

    private final NotificationRepository notificationRepository;
    private final NotificationService notificationService;
    private final JwtSupport jwtSupport;

    public NotificationController(NotificationRepository notificationRepository,
                                   NotificationService notificationService,
                                   JwtSupport jwtSupport) {
        this.notificationRepository = notificationRepository;
        this.notificationService = notificationService;
        this.jwtSupport = jwtSupport;
    }

    @GetMapping
    public ResponseEntity<List<Notification>> listNotifications(HttpServletRequest request) {
        JwtSupport.TokenUser user = jwtSupport.parse(request.getHeader("Authorization"));
        if (user == null) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        List<Notification> notifications = notificationRepository
                .findByTenantIdAndUserId(user.tenantId(), user.userId(),
                        PageRequest.of(0, 30, Sort.by(Sort.Direction.DESC, "createdAt")))
                .getContent();

        return ResponseEntity.ok(notifications);
    }

    @PatchMapping("/{id}/read")
    public ResponseEntity<Map<String, Object>> markAsRead(@PathVariable UUID id, HttpServletRequest request) {
        JwtSupport.TokenUser user = jwtSupport.parse(request.getHeader("Authorization"));
        if (user == null) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        int updated = notificationService.markAsRead(user.tenantId(), user.userId(), List.of(id));
        return ResponseEntity.ok(Map.of("updated", updated));
    }

    @PatchMapping("/read-all")
    public ResponseEntity<Map<String, Object>> markAllAsRead(HttpServletRequest request) {
        JwtSupport.TokenUser user = jwtSupport.parse(request.getHeader("Authorization"));
        if (user == null) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        int updated = notificationService.markAllAsRead(user.tenantId(), user.userId());
        return ResponseEntity.ok(Map.of("updated", updated));
    }
}
