// ============================================================
// Rich Mock Data — simulates real API responses
// ============================================================
import type {
    User,
    Task,
    Project,
    TeamMember,
    StatCardData,
    Activity,
    Notification,
    Plan,
} from '@/types';

// ── Users ────────────────────────────────────────────────────
export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Rayen Lassoued',
        email: '',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rayen',
        role: 'owner',
        createdAt: '2024-01-10T09:00:00Z',
        plan: 'pro',
    },
    {
        id: 'u2',
        name: 'Sarah Chen',
        email: 'sarah@acme.io',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        role: 'admin',
        createdAt: '2024-02-15T09:00:00Z',
        plan: 'pro',
    },
    {
        id: 'u3',
        name: 'Marcus Williams',
        email: 'marcus@acme.io',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
        role: 'member',
        createdAt: '2024-03-01T09:00:00Z',
        plan: 'free',
    },
];

export const mockCurrentUser: User = mockUsers[0];

// ── Projects ─────────────────────────────────────────────────
export const mockProjects: Project[] = [
    {
        id: 'p1',
        name: 'Customer Portal',
        description: 'Self-service portal for enterprise customers',
        status: 'active',
        progress: 68,
        ownerId: 'u1',
        teamIds: ['u1', 'u2', 'u3'],
        dueDate: '2026-04-30T00:00:00Z',
        createdAt: '2026-01-05T00:00:00Z',
        tags: ['react', 'api', 'design'],
        color: '#6366f1',
    },
    {
        id: 'p2',
        name: 'Analytics Dashboard',
        description: 'Real-time analytics and reporting engine',
        status: 'active',
        progress: 42,
        ownerId: 'u2',
        teamIds: ['u1', 'u2'],
        dueDate: '2026-05-15T00:00:00Z',
        createdAt: '2026-01-20T00:00:00Z',
        tags: ['data', 'charts', 'backend'],
        color: '#8b5cf6',
    },
    {
        id: 'p3',
        name: 'Mobile App v2',
        description: 'Next-gen mobile experience for iOS & Android',
        status: 'paused',
        progress: 25,
        ownerId: 'u1',
        teamIds: ['u3'],
        dueDate: '2026-06-30T00:00:00Z',
        createdAt: '2026-02-01T00:00:00Z',
        tags: ['mobile', 'react-native'],
        color: '#f59e0b',
    },
    {
        id: 'p4',
        name: 'API Gateway',
        description: 'Unified API gateway with rate limiting and auth',
        status: 'completed',
        progress: 100,
        ownerId: 'u2',
        teamIds: ['u1', 'u2', 'u3'],
        dueDate: '2026-02-01T00:00:00Z',
        createdAt: '2025-12-01T00:00:00Z',
        tags: ['backend', 'devops'],
        color: '#10b981',
    },
];

// ── Tasks ─────────────────────────────────────────────────────
export const mockTasks: Task[] = [
    {
        id: 't1',
        title: 'Design onboarding flow',
        description: 'Create wireframes and hi-fi designs for new user onboarding',
        status: 'todo',
        priority: 'high',
        projectId: 'p1',
        assigneeId: 'u2',
        dueDate: '2026-03-10T00:00:00Z',
        createdAt: '2026-02-20T00:00:00Z',
        tags: ['design', 'ux'],
        estimatedHours: 12,
    },
    {
        id: 't2',
        title: 'Integrate Stripe billing',
        description: 'Set up Stripe subscriptions, webhooks, and customer portal',
        status: 'in_progress',
        priority: 'urgent',
        projectId: 'p1',
        assigneeId: 'u1',
        dueDate: '2026-03-05T00:00:00Z',
        createdAt: '2026-02-18T00:00:00Z',
        tags: ['backend', 'billing'],
        estimatedHours: 20,
    },
    {
        id: 't3',
        title: 'Write unit tests for auth',
        description: 'Achieve 80% coverage on authentication module',
        status: 'in_progress',
        priority: 'medium',
        projectId: 'p1',
        assigneeId: 'u3',
        dueDate: '2026-03-12T00:00:00Z',
        createdAt: '2026-02-22T00:00:00Z',
        tags: ['testing'],
        estimatedHours: 8,
    },
    {
        id: 't4',
        title: 'Set up CI/CD pipeline',
        description: 'GitHub Actions with automated tests and deployment',
        status: 'review',
        priority: 'high',
        projectId: 'p4',
        assigneeId: 'u1',
        dueDate: '2026-03-01T00:00:00Z',
        createdAt: '2026-02-15T00:00:00Z',
        tags: ['devops'],
        estimatedHours: 6,
    },
    {
        id: 't5',
        title: 'SEO audit and fixes',
        description: 'Run Lighthouse, fix issues, improve Core Web Vitals',
        status: 'done',
        priority: 'low',
        projectId: 'p1',
        assigneeId: 'u2',
        createdAt: '2026-02-10T00:00:00Z',
        tags: ['seo', 'performance'],
        estimatedHours: 4,
    },
    {
        id: 't6',
        title: 'Chart components for analytics',
        description: 'Build reusable Bar, Line, and Doughnut chart components',
        status: 'todo',
        priority: 'medium',
        projectId: 'p2',
        assigneeId: 'u2',
        dueDate: '2026-03-20T00:00:00Z',
        createdAt: '2026-02-25T00:00:00Z',
        tags: ['frontend', 'charts'],
        estimatedHours: 16,
    },
    {
        id: 't7',
        title: 'PostgreSQL schema migration',
        description: 'Add multi-tenancy columns and update indexes',
        status: 'done',
        priority: 'urgent',
        projectId: 'p4',
        assigneeId: 'u1',
        createdAt: '2026-01-28T00:00:00Z',
        tags: ['database', 'backend'],
        estimatedHours: 5,
    },
    {
        id: 't8',
        title: 'Notification system',
        description: 'Real-time notifications via WebSocket',
        status: 'todo',
        priority: 'medium',
        projectId: 'p2',
        dueDate: '2026-04-01T00:00:00Z',
        createdAt: '2026-02-26T00:00:00Z',
        tags: ['backend', 'realtime'],
        estimatedHours: 12,
    },
];

// ── Team Members ──────────────────────────────────────────────
export const mockTeamMembers: TeamMember[] = [
    {
        id: 'tm1',
        userId: 'u1',
        name: 'Rayen Lassoued',
        email: '',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rayen',
        role: 'owner',
        joinedAt: '2024-01-10T09:00:00Z',
        lastActive: '2026-02-27T18:00:00Z',
        tasksCount: 12,
    },
    {
        id: 'tm2',
        userId: 'u2',
        name: 'Sarah Chen',
        email: 'sarah@acme.io',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        role: 'admin',
        joinedAt: '2024-02-15T09:00:00Z',
        lastActive: '2026-02-27T14:30:00Z',
        tasksCount: 8,
    },
    {
        id: 'tm3',
        userId: 'u3',
        name: 'Marcus Williams',
        email: 'marcus@acme.io',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
        role: 'member',
        joinedAt: '2024-03-01T09:00:00Z',
        lastActive: '2026-02-26T11:00:00Z',
        tasksCount: 5,
    },
    {
        id: 'tm4',
        userId: 'u4',
        name: 'Priya Patel',
        email: 'priya@acme.io',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        role: 'member',
        joinedAt: '2024-04-10T09:00:00Z',
        lastActive: '2026-02-25T08:00:00Z',
        tasksCount: 3,
    },
];

// ── Stats ─────────────────────────────────────────────────────
export const mockStats: StatCardData[] = [
    {
        id: 's1',
        label: 'Active Projects',
        value: 4,
        change: 25,
        trend: 'up',
        icon: 'FolderOpen',
        color: 'blue',
    },
    {
        id: 's2',
        label: 'Tasks Completed',
        value: 127,
        change: 18,
        trend: 'up',
        icon: 'CheckCircle',
        color: 'green',
    },
    {
        id: 's3',
        label: 'Team Members',
        value: 4,
        change: 0,
        trend: 'neutral',
        icon: 'Users',
        color: 'purple',
    },
    {
        id: 's4',
        label: 'Hours Logged',
        value: '248h',
        change: -5,
        trend: 'down',
        icon: 'Clock',
        color: 'orange',
    },
];

// ── Activity Feed ─────────────────────────────────────────────
export const mockActivity: Activity[] = [
    {
        id: 'a1',
        type: 'task_completed',
        userId: 'u1',
        userName: 'Rayen Lassoued',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rayen',
        message: 'completed task',
        resourceId: 't7',
        resourceName: 'PostgreSQL schema migration',
        createdAt: '2026-02-27T17:30:00Z',
    },
    {
        id: 'a2',
        type: 'member_joined',
        userId: 'u4',
        userName: 'Priya Patel',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        message: 'joined the workspace',
        createdAt: '2026-02-27T15:00:00Z',
    },
    {
        id: 'a3',
        type: 'task_created',
        userId: 'u2',
        userName: 'Sarah Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        message: 'created task',
        resourceId: 't8',
        resourceName: 'Notification system',
        createdAt: '2026-02-27T12:45:00Z',
    },
    {
        id: 'a4',
        type: 'project_created',
        userId: 'u1',
        userName: 'Rayen Lassoued',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rayen',
        message: 'created project',
        resourceId: 'p3',
        resourceName: 'Mobile App v2',
        createdAt: '2026-02-26T09:00:00Z',
    },
    {
        id: 'a5',
        type: 'comment_added',
        userId: 'u3',
        userName: 'Marcus Williams',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
        message: 'commented on',
        resourceId: 't2',
        resourceName: 'Integrate Stripe billing',
        createdAt: '2026-02-26T08:10:00Z',
    },
];

// ── Notifications ─────────────────────────────────────────────
export const mockNotifications: Notification[] = [
    {
        id: 'n1',
        title: 'Task deadline approaching',
        message: '"Integrate Stripe billing" is due in 6 days',
        read: false,
        type: 'warning',
        createdAt: '2026-02-27T18:00:00Z',
    },
    {
        id: 'n2',
        title: 'New team member',
        message: 'Priya Patel has joined your workspace',
        read: false,
        type: 'info',
        createdAt: '2026-02-27T15:00:00Z',
    },
    {
        id: 'n3',
        title: 'Task completed',
        message: 'Alex completed "PostgreSQL schema migration"',
        read: true,
        type: 'success',
        createdAt: '2026-02-27T17:30:00Z',
    },
];

// ── Pricing Plans ─────────────────────────────────────────────
export const mockPlans: Plan[] = [
    {
        id: 'free',
        name: 'Free',
        price: 0,
        period: 'month',
        features: ['3 projects', '5 team members', '1 GB storage', 'Basic analytics'],
    },
    {
        id: 'pro',
        name: 'Pro',
        price: 19,
        period: 'month',
        features: [
            'Unlimited projects',
            '20 team members',
            '50 GB storage',
            'Advanced analytics',
            'Priority support',
            'Custom domains',
        ],
        highlighted: true,
    },
    {
        id: 'team',
        name: 'Team',
        price: 49,
        period: 'month',
        features: [
            'Unlimited everything',
            '100 team members',
            '500 GB storage',
            'AI-powered insights',
            'SLA guarantee',
            'SSO / SAML',
            'Audit logs',
        ],
    },
];

// ── Chart Data ────────────────────────────────────────────────
export const mockChartData = [
    { label: 'Jan', value: 45 },
    { label: 'Feb', value: 52 },
    { label: 'Mar', value: 38 },
    { label: 'Apr', value: 65 },
    { label: 'May', value: 48 },
    { label: 'Jun', value: 72 },
    { label: 'Jul', value: 61 },
];
